### ISSUE TITLE
Support to get IPAddress with one call

### ISSUE THREAD

**Issue by renanbandeira** [salbahra/cordova-plugin-networkinterface#32]
It would be great if the plugin contained a function to get the first available IPAddress, trying to get wifi IP Address and, if it's not available, gets Carrier IP Address.

**Comment by salbahra** [comment]
I think this could easily be done. In fact I just whipped up a branch with this feature here: https://github.com/salbahra/cordova-plugin-networkinterface/tree/feature/add-single-call-for-wifi-and-carrier-ip. Can you possibly try it out and see if it works for you? Otherwise, I can try to test this later and verify.

**Comment by spyros-88** [comment]
Thanks for adding the generic `getIPAddress` method, it's very helpful!
I tested the method on Google Pixel 2, with Android 9 and it's working fine.

<img width="457" alt="getipaddress" src="https://user-images.githubusercontent.com/15960526/43524982-82c71a10-9598-11e8-832d-4e3b672b2814.png">

Since the feature I am developing will go into production, it will go through the QA team.
I will let you know if any issue occurs, along with the list of the devices that was tested on.

**Comment by evergreen-lee-campbell** [comment]
Any news on whether or not this is getting PR'd in?

**Comment by salbahra** [comment]
Sorry for the delays, merged in now
